### ISSUE TITLE
TransferSender test fails

### ISSUE THREAD

**Issue by lawlawlaw** [commerceblock/mercury-wallet#61]
● StateChain Entity › TransferSender

    Expected public key to be an Uint8Array with length [33, 65]

      192 | export const decryptECIESx1 = (secret_key: string, encryption: string): string => {
      193 |   let enc = new Uint32Array(Buffer.from(encryption, "hex"))
    > 194 |   let dec = decrypt(secret_key, Buffer.from(enc));
          |             ^
      195 |   return dec.toString("hex")  // un-JSONify
      196 | }
      197 |

      at assert (node_modules/secp256k1/lib/index.js:18:20)
      at isUint8Array (node_modules/secp256k1/lib/index.js:28:7)
      at Object.publicKeyConvert (node_modules/secp256k1/lib/index.js:128:7)
      at new PublicKey (node_modules/eciesjs/dist/keys/PublicKey.js:11:61)
      at decrypt (node_modules/eciesjs/dist/index.js:19:24)
      at decryptECIESx1 (src/wallet/util.ts:194:13)
      at transferSender (src/wallet/mercury/transfer.ts:102:16)
      at Wallet.transfer_sender (src/wallet/wallet.ts:346:27)
      at Object.<anonymous> (src/wallet/test/mercury.test.js:92:25)

**Comment by 86667** [comment]
Fixed [here](https://github.com/commerceblock/mercury-wallet/commit/71333f4bbd3b79ba258b415958bc6b9ffb9478d1).
